-- Script para criar tabelas de Frango de Corte e Ração por Insumo
-- Dashboards para módulos 3 e 6

-- =====================================================
-- TABELA: POCWEB_DASH_FRANGO_CORTE (Módulo 3)
-- =====================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE POCWEB_DASH_FRANGO_CORTE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE POCWEB_DASH_FRANGO_CORTE (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LOTE NUMBER,
    DATA_ALOJAMENTO DATE,
    ALOJADAS NUMBER,
    ABATIDAS NUMBER,
    MORTE_PERC NUMBER(10,2),
    IDADE NUMBER(10,2),
    PESO_MEDIO NUMBER(10,3),
    CA NUMBER(10,3),
    CAC NUMBER(10,3),
    VIABILIDADE NUMBER(10,2),
    GPD NUMBER(10,2),
    IEP NUMBER(10,2),
    PESO_TOTAL NUMBER(12,2),
    TIPO_GALPAO VARCHAR2(50),
    IEL NUMBER
);

-- =====================================================
-- TABELA: POCWEB_DASH_RACAO_INSUMO (Módulo 6)
-- =====================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE POCWEB_DASH_RACAO_INSUMO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE POCWEB_DASH_RACAO_INSUMO (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRODUTO_FINAL VARCHAR2(200),
    INGREDIENTE VARCHAR2(200),
    QTD_DOSADA NUMBER(15,3),
    CUSTO NUMBER(15,4)
);

-- =====================================================
-- CONFIGURAÇÕES DE DASHBOARD
-- =====================================================
DELETE FROM POCWEB_DASH_CONFIG WHERE DASHBOARD_KEY IN ('frango_corte', 'racao_insumo');

INSERT INTO POCWEB_DASH_CONFIG (MODULO_ID, MODULO_NOME, DASHBOARD_KEY, ATIVO)
VALUES (3, 'Frango de Corte', 'frango_corte', 1);

INSERT INTO POCWEB_DASH_CONFIG (MODULO_ID, MODULO_NOME, DASHBOARD_KEY, ATIVO)
VALUES (6, 'Fabrica de Racao', 'racao_insumo', 1);

COMMIT;

-- Verificar tabelas criadas
SELECT table_name FROM user_tables WHERE table_name LIKE 'POCWEB_DASH%';
SELECT * FROM POCWEB_DASH_CONFIG;
