INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846471', */ '210', 'CAIXCA02', '-', 'Caixa 02', 'Caixa 02', '205', '0', '10', '0', '340', 'CAIXA', '70', '0', '1', '0', '0', '0', '0', '0', '0', '65', '1', '1', '0', '0', '2', '0', '1', '1', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CAIXCA02', 'BVL', '1', '0', '210006', '65', '0', '2', '10', '0', '1', '1', '1', '0', '0', '340', '205'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846472', */ '210', 'BLCOTPDO', 'Bloqueio Comercial', 'Bloqueio Comercial', 'Bloqueio Comercial', '230', '25', '25', '0', '150', 'SIMNAO', '80', '0', '1', ',0;-,0', '0', '0', '0', '0', '0', '0', '40', '0', '0', '1', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'BLCOTPDO', 'S', '1', '0', '210007', '40', '0', '1', '25', '0', '1', '0', '0', '0', '25', '150', '230'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846473', */ '210', 'BLFITPDO', 'Bloqueio Financeiro', 'Bloqueio Financeiro', 'Bloqueio Financeiro', '230', '0', '185', '0', '150', 'SIMNAO', '90', '0', '1', '0', '0', '0', '0', '0', '0', '40', '0', '0', '1', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'BLFITPDO', 'S', '1', '0', '210008', '40', '0', '1', '185', '0', '1', '0', '0', '0', '0', '150', '230'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, NOANCAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846474', */ '210', 'NOMETPDO', 'Nome', 'Nome do Documento', 'Nome', '40', '0', '25', '0', '310', 'Texto040', '20', '0', '1', '0', '0', '0', '0', '0', '0', '100', 'XXX', '0', '0', '2', '2', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'NOMETPDO', 'NOMETPDO', 'E', '1', '0', '210001', '100', '2', '2', '25', '0', '1', '0', '0', '0', '0', '310', '40'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, NOANCAMP, EXPRCAMP, COMPCAMP, INICCAMP, ID__CAMP, VARECAMP, VAGRCAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846475', */ '210', 'TIPOTPDO', 'Tipo', 'Tipo do Documento', 'Tipo', '95', '0', '25', '0', '150', 'Char2', '30', '0', '1', '0', '0', '0', '0', '0', '0', '100', 'XXX', '0', '0', '1', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'TIPOTPDO', 'TIPOTPDO', 'VA-INTE0001-SELECT (CASE WHEN {CC-TIPOTPDO} IN (''BO'', ''CR'', ''DU'', ''DT'', ''CC'', ''CD'') THEN 1 ELSE 0 END) AS VALO FROM DUAL
IF-INIC0001-{VA-INSERIND}
  CS-SF16TPDO-{VA-INTE0001}
IF-FINA0001-

IF-INIC0001-{VA-INTE0001}
  CSDSF16TPDO-1
IF-ELSE0001-
  CSDSF16TPDO-0
  CS-SF16TPDO-0
IF-FINA0001-
', 'C', '1', '0', 'Dinheiro
Duplicata
Boleto
Cheque
Crédito em Conta
Débito em Conta
DOC/TED
Expedição
Cartão Crédito
Cartão Débito
Nota de Débito
Ordem de Pagamento', 'DI
DU
BO
CH
CR
DE
DT
EX
CC
CD
ND
OP', '210002', '100', '0', '1', '25', '0', '1', '0', '0', '0', '0', '150', '95'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846476', */ '210', 'CAIXCA01', '-', 'Caixa', 'Caixa', '15', '0', '10', '0', '340', 'CAIXA', '10', '0', '1', '0', '0', '0', '0', '0', '0', '175', '1', '1', '0', '0', '2', '0', '3', '3', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CAIXCA01', 'BVL', '1', '0', '210000', '175', '0', '2', '10', '0', '1', '3', '3', '0', '0', '340', '15'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, NOANCAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846477', */ '210', 'ATIVTPDO', 'Ativo', 'Tipo de Documento Ativo', 'Ativo', '150', '0', '25', '0', '150', 'SimNao', '50', '0', '1', '0', '0', '0', '0', '0', '1', '100', 'XXX', '0', '0', '1', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'ATIVTPDO', 'ATIVTPDO', 'S', '1', '0', '210004', '100', '0', '1', '25', '0', '1', '0', '0', '0', '0', '150', '150'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, COMPCAMP, INICCAMP, ID__CAMP, VARECAMP, VAGRCAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846478', */ '210', 'PDA_TPDO', 'Disponível no SAGMob', 'Disponível no SAGMob', 'Disponível no SAGMob', '150', '0', '185', '0', '150', 'TEXTO010', '60', '0', '1', '0', '0', '0', '0', '0', '0', '100', '0', '0', '1', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'PDA_TPDO', 'C', '1', '0', 'Sim
Não', '1
0', '210005', '100', '0', '1', '185', '0', '1', '0', '0', '0', '0', '150', '150'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, NOANCAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP, SALTCAMP, SCOECAMP, SCOLCAMP, SESQCAMP, SFIXCAMP, SGUICAMP, SLIECAMP, SLINCAMP, SMESCAMP, SMTOCAMP, STAMCAMP, STOPCAMP
) VALUES (/* '1216846479', */ '210', 'ORDETPDO', 'Ordem', 'Ordem', 'Ordem', '95', '0', '185', '0', '150', 'Inteiro', '40', '0', '1', ',0;-,0', '0', '0', '0', '0', '0', '0', '100', 'XXX', '0', '0', '1', '2', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'ORDETPDO', 'ORDETPDO', 'N', '1', '0', '210003', '100', '2', '1', '185', '0', '1', '0', '0', '0', '0', '150', '95'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP
) VALUES (/* '1216846480', */ '210', 'CAIXCA03', '-', '-', '-', '285', '0', '10', '0', '340', 'CAIXA', '100', '0', '1', '0', '0', '0', '0', '0', '0', '65', '1', '1', '0', '0', '1', '0', '0', '1', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CAIXCA03', 'BVL', '1', '0', '1216861847'
)
--EXEC

INSERT INTO sistcamp (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, COMPCAMP, INICCAMP, ID__CAMP, SGCHCAMP
) VALUES (/* '1216846481', */ '210', 'SF16TPDO', 'Reg. 1601 (SPED Fiscal)', 'Inclui no Reg. 1601 - Operações com instrumentos de pagamentos eletrônicos do SPED Fiscal os pagamentos lançados com esse tipo', 'Reg. 1601 (SPED Fiscal)', '310', '0', '25', '0', '150', 'SIMNAO', '110', '0', '1', '0', '0', '0', '0', '0', '0', '40', '0', '0', '1', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'SF16TPDO', 'S', '1', '0', '1216861822'
)
--EXEC

