INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514007', */ '514', 'ATUANCM_', 'Não Sugerir atualizar NCM do produto', 'Não Sugerir atualizar NCM quando for divergente do informado pelo forncedor no XML', 'ATUANCM_', '175', '0', '345', '0', '310', 'EDITOR', '53', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'ATUANCM_', '1', '0', '-514004', '175', '0', '25', '0', '310', '100', '1', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, SQL_CAMP, INICCAMP, CODTTABE, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514014', */ '514', 'TPMVCUPR', 'Tipo de Mov. Entrada de Produção', 'Tipo de Mov. Entrada de Produção', 'Entrada_de_Producao', '40', '0', '25', '0', '282', 'INFORMAÇÃO', '70', '0', '2', 'IT', ',0;-,0', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'TPMVCUPR', 'SELECT POCATPMV.CODITPMV, POCATPMV.NOMETPMV
FROM POCATPMV LEFT JOIN POCATPDO ON POCATPDO.CODITPDO = POCATPMV.CODITPDO
WHERE (POCATPMV.ATIVTPMV = 1) AND (POCATPMV.LOCATPMV = ''E'') AND (POCATPMV.DESCTPMV = ''E'') 


ORDER BY POCATPMV.NOMETPMV

', '1', '170', '0', '-514011', '40', '0', '25', '0', '282', '100', '2', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514022', */ '514', 'FILTRAPL', 'Filtra Ramo Ativ./Plano de Contas', 'Filtra Ramo Ativ./Plano de Contas', 'Filtra Ramo Ativ./Plano de Contas', '230', '0', '25', '0', '310', 'EDITOR', '140', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'FILTRAPL', '1', '0', '-514020', '230', '0', '25', '0', '310', '100', '2', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514006', */ '514', 'LIMOENPE', 'Libera Bloqueio de Valor na Entrada de Moeda Diferente', 'Libera Valor na Entrada de Moeda Diferente', 'Libera_Valor_na_Entrada_de_Moeda_Diferente', '175', '0', '25', '0', '310', 'EDITOR', '50', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'LIMOENPE', '1', '0', '-514004', '175', '0', '25', '0', '310', '100', '1', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, EXPRCAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514018', */ '514', 'ESPEGRPE', 'Configura', 'Configurar individualmente os usuários que podem Movimentar Estoque Retroativo', 'Configura', '95', '0', '535', '0', '150', 'BOTÃO', '106', '0', '2', 'BTN', '131', '0', '0', '0', '0', '0', '0', '21', '0', '1', '1', '2', '1', '0', 'MS Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '7', '0', '0', '10', '0', 'ESPEGRPE', 'FOM795
', '1', '0', '-514016', '95', '0', '535', '0', '150', '21', '2', '1', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, VARECAMP, VAGRCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514002', */ '514', 'CONTPARA', 'Tolerância Contrato', 'Tolerancia_Contrato', '40', '0', '25', '0', '150', 'EDITOR', '20', '0', '1', 'EC', '0', '0', '0', '0', '0', '0', '100', '0', '0', '1', '3', '0', '0', 'MS Sans Serif', '16711680', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CONTPARA', '1', '0', 'Não Validar
Avisar
Bloquear
', 'NAO
AVISAR
BLOQUEAR', '-514001', '40', '0', '25', '0', '150', '100', '1', '1', '3', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514004', */ '514', 'SEPAMVCX', 'Separa Custos por Mov. de Estoque', 'Separa Custos por Mov. de Estoque', 'Separa_custos_por_Mov_de_Estoque', '120', '25', '25', '0', '310', 'EDITOR', '40', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'SEPAMVCX', '1', '0', '-514003', '120', '25', '25', '0', '310', '100', '1', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, EXPRCAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514017', */ '514', 'ESPEESTO', 'Configurar por Pessoa', 'Configurar por Pessoa: Quando marcado, permite cadastrar a pessoa que irá poder Movimentar Estoque Retroativo através do botão Configurar', 'Configurar por Pessoa', '95', '0', '375', '350', '150', 'EDITOR', '105', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '40', '0', '0', '1', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'ESPEESTO', 'IF-INIC0001-{ES-ESPEESTO}
  ITDPE_MV_ES-0
  BTDESPEGRPE-1
  IT-PE_MV_ES-NULL
IF-ELSE0001-
  ITDPE_MV_ES-1
  BTDESPEGRPE-0
IF-FINA0001-
', '1', '0', '-514015', '95', '0', '375', '30', '150', '40', '2', '1', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514023', */ '514', 'OBRIGAMANIFESTO', 'Realizar a operação de Manifesto de Recebimento', 'Realizar a operação de Manifesto de Recebimento', 'Realizar a operação de Manifesto de Recebimento', '230', '0', '345', '0', '310', 'EDITOR', '142', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '40', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'OBRIGAMANI', '1', '0', '-514022', '285', '0', '25', '0', '310', '40', '2', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514025', */ '514', 'RETPISCO', 'Não Faz Retenção de PIS e COFINS', 'Não Faz Retenção de PIS e COFINS', 'Não Faz Retenção de PIS e COFINS', '285', '0', '345', '0', '310', 'EDITOR', '144', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '40', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'RETPISCO', '1', '0', '-514026', '365', '0', '375', '0', '310', '40', '2', '2', '0', '0', '0', '1'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514027', */ '514', 'FILTACAB', 'Filtrar Apenas Produtos Não Acabados', 'Não irá mostrar produtos acabados na tela da industrialização', 'Filtrar Apenas Produtos Não Acabados', '365', '25', '25', '0', '310', 'EDITOR', '151', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '2', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'FILTACAB', '1', '0', '-514025', '365', '25', '25', '0', '310', '100', '2', '2', '0', '0', '0', '1'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, LBCXCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514013', */ '514', 'CA03PARA', 'Custo de Produção', 'Caixa', 'Caixa', '15', '0', '10', '0', '340', 'CAIXA', '69', '0', '2', 'BVL', '0', '0', '0', '0', '0', '0', '120', '1', '1', '0', '1', '2', '0', '2', '8', 'MS Sans Serif', '0', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CA03PARA', '1', '0', '1', '-514010', '15', '0', '10', '0', '340', '120', '2', '2', '0', '2', '8', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, SQL_CAMP, INICCAMP, CODTTABE, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514016', */ '514', 'PE_MV_ES', 'Movimentar Estoque Retroativo', 'Grupo de Usuários que podem Movimentar Estoque Retroativo', 'Movimentar Estoque Retroativo', '40', '0', '375', '30', '282', 'INFORMAÇÃO', '100', '0', '2', 'IT', ',0;-,0', '0', '0', '0', '100', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'PE_MV_ES', 'SELECT POCAGRUS.CODIGRUS, POCAGRUS.NOMEGRUS
FROM POCAGRUS
WHERE (POCAGRUS.ATIVGRUS = 1)


ORDER BY POCAGRUS.NOMEGRUS
', '1', '97', '0', '-514012', '40', '0', '375', '30', '282', '100', '2', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, EXPRCAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514010', */ '514', 'OBCH_NFE', 'Obrigatoriedade Chave NF-e', 'Obrigatoriedade Chave NF-e', 'Obrigatoriedade Chave NF-e', '340', '0', '25', '0', '310', 'EDITOR', '63', '0', '1', 'ES', ',0.00;-,0.00', '0', '0', '2', '0', '0', '0', '100', '0', '0', '2', '2', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'OBCH_NFE', 'IF-INIC0001-IF({ES-OBCH_NFE}=0,1,0)
  ES-VLCH_NFE-0
IF-FINA0001-
', '1', '0', '-514007', '340', '0', '25', '0', '310', '100', '1', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514029', */ '514', 'FIABNFIN', 'Filtrar ao abrir Tela - Importação NFe(Padrão)', 'Filtrar ao abrir Tela - Importação NFe(Padrão)', 'Filtrar ao abrir Tela - Importação NFe(Padrão)', '445', '25', '25', '0', '310', 'EDITOR', '210', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '40', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'FIABNFIN', '1', '0', '-514021', '445', '25', '25', '0', '310', '40', '2', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514024', */ '514', 'INATCONT', 'Inativar Contrato Zerado', 'Inativar Contrato Zerado', 'Inativar Contrato Zerado', '285', '0', '25', '0', '310', 'EDITOR', '143', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '40', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'INATCONT', '1', '0', '-514023', '285', '0', '375', '0', '310', '40', '2', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514012', */ '514', 'VLPSSISS', 'Libera Pessoa ISSQN', 'Libera pessoa ISSQN', 'Libera pessoa ISSQN', '450', '0', '25', '0', '310', 'EDITOR', '67', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'VLPSSISS', '1', '0', '-514009', '450', '0', '25', '0', '310', '100', '1', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514008', */ '514', 'VLPRIMPO', 'Valida Preenchimento de CFOP, Natureza, CST, ICMS, IPI, PIS e COFINS', 'Valida Preenchimento de CST, ICMS, IPI, PIS e COFINS. (Também verifica o preenchimento do campo CFOP e Natureza)', 'Valida_Preenchimento_de_CSTICMS_IPI_PIS_e_COFINS', '230', '0', '25', '0', '470', 'EDITOR', '55', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '3', '1', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'VLPRIMPO', '1', '0', '-514005', '230', '0', '25', '0', '470', '100', '1', '3', '1', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, EXPRCAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514009', */ '514', 'VLCH_NFE', 'Valida Chave da NF-e', 'Valida Chave da NF-e', 'Valida_Chave_da_NF_e', '285', '0', '25', '0', '310', 'EDITOR', '60', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '2', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'VLCH_NFE', 'IF-INIC0001-IF({ES-VLCH_NFE}=1,1,0)
  ES-OBCH_NFE-1
IF-FINA0001-
', '1', '0', '-514006', '285', '0', '25', '0', '310', '100', '1', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514021', */ '514', 'USTPMVDV', 'Usa Tipo Movimento Devolução no Caso de Integrado', 'Caso esta opção esteja marcado quando for realizar uma entrada o Tipo Movimento será de Devolução', 'usa_tpmv_devo_integrado', '175', '0', '345', '0', '310', 'EDITOR', '130', '0', '2', 'ES', '0', '0', '0', '0', '0', '1', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'USTPMVDV', '1', '0', '-514019', '175', '0', '375', '0', '310', '100', '2', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514011', */ '514', 'ANLBPARA', 'Análise Laboratorial', 'Análise Laboratorial', 'Análise Laboratorial', '395', '0', '25', '0', '310', 'EDITOR', '65', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '2', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'ANLBPARA', '1', '0', '-514008', '395', '0', '25', '0', '310', '100', '1', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, LBCXCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514001', */ '514', 'CA01PARA', 'Tolerância Contrato', 'Caixa', 'Caixa', '15', '0', '10', '0', '660', 'CAIXA', '10', '0', '1', 'BVL', ',0;-,0', '0', '0', '0', '0', '0', '0', '65', '1', '1', '0', '0', '4', '0', '1', '0', 'MS Sans Serif', '0', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CA01PARA', '1', '0', '1', '-514000', '15', '0', '10', '0', '690', '65', '1', '4', '0', '1', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514020', */ '514', 'GEESEMIS', 'Baixar Estoque na Geração da Nota', 'Baixar estoque na geração da nota', 'Baixar_estoque_na_geracao_da_nota', '175', '25', '25', '0', '310', 'EDITOR', '120', '0', '2', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'GEESEMIS', '1', '0', '-514018', '175', '25', '25', '0', '310', '100', '2', '2', '0', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514005', */ '514', 'ESTOINVE', 'Oculta Informação do Estoque no Inventário', 'Oculta Informação do Estoque no Inventário', 'ESTOINVE', '120', '0', '345', '0', '310', 'EDITOR', '45', '0', '1', 'ES', '0', '0', '0', '0', '0', '0', '100', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'ESTOINVE', '1', '0', '-514003', '120', '25', '25', '0', '310', '100', '1', '2', '2', '0', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MASCCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, LBCXCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514003', */ '514', 'CA02PARA', 'Entradas e Entrada Pedido de Compra', 'Caixa', 'Caixa', '95', '0', '10', '0', '660', 'CAIXA', '25', '0', '1', 'BVL', ',0;-,0', '0', '0', '0', '0', '0', '0', '395', '1', '1', '0', '0', '4', '0', '7', '0', 'MS Sans Serif', '0', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CA02PARA', '1', '0', '1', '-514002', '95', '0', '10', '0', '690', '390', '1', '4', '0', '7', '0', '0'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, LBCXCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514015', */ '514', 'CA04PARA', 'Grupos de Usuário p/', 'Caixa', 'Caixa', '15', '0', '360', '0', '340', 'CAIXA', '75', '0', '2', 'BVL', '0', '0', '0', '0', '0', '0', '120', '1', '1', '0', '1', '2', '0', '2', '8', 'MS Sans Serif', '0', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CA04PARA', '1', '0', '1', '-514014', '15', '0', '360', '0', '340', '120', '2', '2', '0', '2', '8', '1'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, LBCXCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514019', */ '514', 'CA05PARA', 'Nota Fiscal', 'Caixa', 'Caixa', '150', '0', '10', '0', '690', 'CAIXA', '109', '0', '2', 'BVL', '0', '0', '0', '0', '0', '0', '175', '1', '1', '0', '1', '4', '0', '3', '8', 'MS Sans Serif', '0', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CA05PARA', '1', '0', '1', '-514017', '150', '0', '10', '0', '690', '175', '2', '4', '0', '3', '8', '1'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, LBCXCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514026', */ '514', 'CA06PARA', 'Industrialização', 'Caixa', 'Caixa', '340', '0', '10', '0', '690', 'CAIXA', '145', '0', '2', 'BVL', '0', '0', '0', '0', '0', '0', '65', '1', '1', '0', '1', '4', '0', '1', '8', 'MS Sans Serif', '0', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CA06PARA', '1', '0', '1', '-514024', '340', '0', '10', '0', '690', '65', '2', '4', '0', '1', '8', '1'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, FORMCAMP, ESTICAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, LBCXCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514028', */ '514', 'CAIMPARA', 'Importação de NFe', 'Importação de NFe', 'Importação de NFe', '420', '0', '10', '0', '690', 'CAIXA', '200', '0', '2', 'BVL', '0', '0', '0', '0', '0', '0', '65', '1', '1', '0', '1', '4', '0', '1', '8', 'MS Sans Serif', '0', '1', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'CAIMPARA', '1', '0', '1', '1216857854', '420', '0', '10', '0', '690', '65', '2', '4', '0', '1', '8', '1'
)
--EXEC

INSERT INTO sistCAMP (/* CODICAMP, */ CODITABE, NOMECAMP, LABECAMP, HINTCAMP, NOSQCAMP, TOPOCAMP, MTOPCAMP, ESQUCAMP, MESQCAMP, TAMACAMP, TIPOCAMP, ORDECAMP, OBRICAMP, GUIACAMP, COMPCAMP, MINICAMP, MAXICAMP, DECICAMP, DROPCAMP, PESQCAMP, PADRCAMP, ALTUCAMP, DESACAMP, FIXOCAMP, COLUCAMP, COESCAMP, LINHCAMP, LIESCAMP, LFONCAMP, LCORCAMP, LESTCAMP, LEFECAMP, CFONCAMP, CTAMCAMP, CCORCAMP, CESTCAMP, CEFECAMP, LTAMCAMP, INTECAMP, EXISCAMP, TAGQCAMP, PERSCAMP, NAMECAMP, INICCAMP, ID__CAMP, VARECAMP, VAGRCAMP, SGCHCAMP, STOPCAMP, SMTOCAMP, SESQCAMP, SMESCAMP, STAMCAMP, SALTCAMP, SGUICAMP, SCOLCAMP, SCOECAMP, SLINCAMP, SLIECAMP, SFIXCAMP
) VALUES (/* '514030', */ '514', 'TPCOMVFI', 'Tipo Competência (Parcelas)', 'Tipo Competência (Parcelas)', 'Tipo Competência (Parcelas)', '445', '0', '345', '0', '310', 'EDITOR', '220', '0', '2', 'EC', '0', '0', '0', '0', '0', '0', '40', '0', '0', '2', '0', '0', '0', 'Ms Sans Serif', '0', '0', '0', 'Ms Sans Serif', '8', '0', '0', '0', '8', '0', '0', '10', '0', 'TPCOMVFI', '1', '0', 'Vencimento
Emissão
Recebimento', 'V
E
R', '-514021', '445', '25', '375', '0', '310', '40', '2', '2', '0', '0', '0', '0'
)
--EXEC

