CREATE OR REPLACE VIEW POCATPMV (CODITPMV, NOMETPMV, CODITPDO, ATIVTPMV, LOCATPMV, DESCTPMV)
AS
SELECT 1, 'Entrada', 1, 1, 'E', 'E'
FROM DUAL
--EXEC

CREATE OR REPLACE VIEW POCATPDO (CODITPDO, NOMETPDO)
AS
SELECT 1, 'Dinheiro'
FROM DUAL
--EXEC

CREATE OR REPLACE VIEW POCAGRUS (CODIGRUS, NOMEGRUS, ATIVGRUS)
AS
SELECT 1, 'Administradores', 1
FROM DUAL
--EXEC
