
--  *************************************************
--  *** SAG - Tabelas ***

--> 001 Tabela: SISTTABE
------------------------------------------------------
CREATE TABLE SISTTABE (CODITABE Int IDENTITY (1, 1) NOT NULL);
--EXECERRO
ALTER TABLE SISTTABE ADD CONSTRAINT PK_SISTTABE PRIMARY KEY (CODITABE);
--EXECERRO
ALTER TABLE SISTTABE ADD NOMETABE VarChar(250);
--EXECERRO
ALTER TABLE SISTTABE ADD FORMTABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD CAPTTABE VarChar(250);
--EXECERRO
ALTER TABLE SISTTABE ADD HINTTABE VarChar(250);
--EXECERRO
ALTER TABLE SISTTABE ADD GRAVTABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD CHAVTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD BOT1TABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD BOT2TABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD BOT3TABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD SQL1TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD NOM1TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD SQL2TABE VarChar(050);
--EXECERRO
ALTER TABLE SISTTABE ADD NOM2TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD SQL3TABE VarChar(050);
--EXECERRO
ALTER TABLE SISTTABE ADD NOM3TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD SQL4TABE VarChar(050);
--EXECERRO
ALTER TABLE SISTTABE ADD NOM4TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD ULTITABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD CONSTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD MENUTABE VarChar(025);
--EXECERRO
ALTER TABLE SISTTABE ADD ATALTABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD REL1TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD REL2TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD REL3TABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD ORDETABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD SISTTABE VarChar(250);
--EXECERRO
ALTER TABLE SISTTABE ADD ALTUTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD TAMATABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD CABETABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD SUB_TABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD FIGUTABE Image;
--EXECERRO
ALTER TABLE SISTTABE ADD PAOKTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD MEPETABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD CLICTABE VarChar(025);
--EXECERRO
ALTER TABLE SISTTABE ADD GETATABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD TPGRTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD EDITTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD OK__TABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD SERITABE VarChar(100);
--EXECERRO
ALTER TABLE SISTTABE ADD CLONTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD GUI1TABE VarChar(100);
--EXECERRO
ALTER TABLE SISTTABE ADD GUI2TABE VarChar(250);
--EXECERRO
ALTER TABLE SISTTABE ADD FIXOTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD ULNUTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD ULDATABE DateTime;
--EXECERRO
ALTER TABLE SISTTABE ADD FIATTABE Image;
--EXECERRO
ALTER TABLE SISTTABE ADD SIGLTABE VarChar(004);
--EXECERRO
ALTER TABLE SISTTABE ADD APATTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD LANCTABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD PDATTABE DateTime;
--EXECERRO
ALTER TABLE SISTTABE ADD PSISTABE VarChar(3);
--EXECERRO
ALTER TABLE SISTTABE ADD PUSUTABE VarChar(3);
--EXECERRO
ALTER TABLE SISTTABE ADD PEMPTABE VarChar(3);
--EXECERRO
ALTER TABLE SISTTABE ADD PARATABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD VERSTABE VarChar(040);
--EXECERRO
ALTER TABLE SISTTABE ADD ATCATABE VarChar(250);
--EXECERRO
ALTER TABLE SISTTABE ADD EPERTABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD GRCOTABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD APOSTABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD EGRATABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD ID__TABE Float;
--EXECERRO
ALTER TABLE SISTTABE ADD SHOWTABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD SAG_TABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD USUATABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD CODIPRAT Int;
--EXECERRO
ALTER TABLE SISTTABE ADD SGCHTABE VarChar(050);
--EXECERRO
ALTER TABLE SISTTABE ADD SGBUTABE VarChar(050);
--EXECERRO
ALTER TABLE SISTTABE ADD SGTBTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD RESPTABE VarChar(100);
--EXECERRO
ALTER TABLE SISTTABE ADD SGCITABE VarChar(100);
--EXECERRO
ALTER TABLE SISTTABE ADD STAMTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD SALTTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD SFIXTABE Int;
--EXECERRO
ALTER TABLE SISTTABE ADD AJPETABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD AJUDTABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD OBS_TABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD INSETABE VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTTABE ADD GRIDTABE VARCHAR(MAX);
--EXECERRO
------------------------------------------------------




--  *************************************************
--  *** SAG - Tabelas ***

--> 001 Tabela: SISTCONS
------------------------------------------------------
CREATE TABLE SISTCONS (CODICONS Int IDENTITY (1, 1) NOT NULL);
--EXECERRO
ALTER TABLE SISTCONS ADD CONSTRAINT PK_SISTCONS PRIMARY KEY (CODICONS);
--EXECERRO
ALTER TABLE SISTCONS ADD CODITABE Int;
--EXECERRO
ALTER TABLE SISTCONS ADD NOMECONS VarChar(250);
--EXECERRO
ALTER TABLE SISTCONS ADD SQL1CONS VarChar(100);
--EXECERRO
ALTER TABLE SISTCONS ADD SQL2CONS VarChar(100);
--EXECERRO
ALTER TABLE SISTCONS ADD SQL3CONS VarChar(100);
--EXECERRO
ALTER TABLE SISTCONS ADD SQL4CONS VarChar(100);
--EXECERRO
ALTER TABLE SISTCONS ADD NOM1CONS VarChar(040);
--EXECERRO
ALTER TABLE SISTCONS ADD NOM2CONS VarChar(040);
--EXECERRO
ALTER TABLE SISTCONS ADD NOM3CONS VarChar(040);
--EXECERRO
ALTER TABLE SISTCONS ADD NOM4CONS VarChar(040);
--EXECERRO
ALTER TABLE SISTCONS ADD ACCECONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD SERVCONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD SQL5CONS VarChar(250);
--EXECERRO
ALTER TABLE SISTCONS ADD SQL6CONS VarChar(250);
--EXECERRO
ALTER TABLE SISTCONS ADD NOM5CONS VarChar(040);
--EXECERRO
ALTER TABLE SISTCONS ADD NOM6CONS VarChar(040);
--EXECERRO
ALTER TABLE SISTCONS ADD TEMPCONS VarChar(010);
--EXECERRO
ALTER TABLE SISTCONS ADD ERROCONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD ULNUCONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD ULDACONS DateTime;
--EXECERRO
ALTER TABLE SISTCONS ADD SQL_CONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD BUSCCONS VarChar(250);
--EXECERRO
ALTER TABLE SISTCONS ADD APATCONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD ATIVCONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD AJUDCONS VarChar(4000);
--EXECERRO
ALTER TABLE SISTCONS ADD AJPECONS VarChar(4000);
--EXECERRO
ALTER TABLE SISTCONS ADD AJSGCONS VarChar(4000);
--EXECERRO
ALTER TABLE SISTCONS ADD PDATCONS DateTime;
--EXECERRO
ALTER TABLE SISTCONS ADD PSISCONS VarChar(3);
--EXECERRO
ALTER TABLE SISTCONS ADD PUSUCONS VarChar(3);
--EXECERRO
ALTER TABLE SISTCONS ADD PEMPCONS VarChar(3);
--EXECERRO
ALTER TABLE SISTCONS ADD WHERCONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD FILTCONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD VERSCONS VarChar(040);
--EXECERRO
ALTER TABLE SISTCONS ADD ID__CONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD SAG_CONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD CODIGENE Int;
--EXECERRO
ALTER TABLE SISTCONS ADD ESTRCONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD EXTRCONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD USUACONS VarChar(3);
--EXECERRO
ALTER TABLE SISTCONS ADD TABECONS VarChar(010);
--EXECERRO
ALTER TABLE SISTCONS ADD CODIPRAT Int;
--EXECERRO
ALTER TABLE SISTCONS ADD SGCHCONS VarChar(050);
--EXECERRO
ALTER TABLE SISTCONS ADD SGBUCONS VarChar(050);
--EXECERRO
ALTER TABLE SISTCONS ADD SGTBCONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD RESPCONS VarChar(100);
--EXECERRO
ALTER TABLE SISTCONS ADD SGCICONS VarChar(100);
--EXECERRO
ALTER TABLE SISTCONS ADD WHTECONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD WHCACONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD ORBYCONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD ORTECONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD ORCACONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD ORDECONS Int;
--EXECERRO
ALTER TABLE SISTCONS ADD TXDECONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD VARCHAR(MAX)CONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD DESFCONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD TXRECONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD SQRECONS VARCHAR(MAX);
--EXECERRO
ALTER TABLE SISTCONS ADD SQDECONS VARCHAR(MAX);
--EXECERRO
------------------------------------------------------




--  *************************************************
--  *** SAG - Tabelas ***

--> 001 Tabela: POCATPDO
------------------------------------------------------
CREATE TABLE POCATPDO (CODITPDO Int IDENTITY (1, 1) NOT NULL);
--EXECERRO
ALTER TABLE POCATPDO ADD CONSTRAINT PK_POCATPDO PRIMARY KEY (CODITPDO);
--EXECERRO
ALTER TABLE POCATPDO ADD NOMETPDO VarChar(040);
--EXECERRO
ALTER TABLE POCATPDO ADD TIPOTPDO VarChar(20);
--EXECERRO
ALTER TABLE POCATPDO ADD ATIVTPDO Int;
--EXECERRO
ALTER TABLE POCATPDO ADD ORDETPDO Int;
--EXECERRO
ALTER TABLE POCATPDO ADD CTPDTPDO VarChar(10);
--EXECERRO
ALTER TABLE POCATPDO ADD XTPDTPDO VarChar(10);
--EXECERRO
ALTER TABLE POCATPDO ADD PDATTPDO DateTime;
--EXECERRO
ALTER TABLE POCATPDO ADD PSISTPDO VarChar(3);
--EXECERRO
ALTER TABLE POCATPDO ADD PUSUTPDO VarChar(3);
--EXECERRO
ALTER TABLE POCATPDO ADD PEMPTPDO VarChar(3);
--EXECERRO
ALTER TABLE POCATPDO ADD PDA_TPDO Float;
--EXECERRO
ALTER TABLE POCATPDO ADD BLCOTPDO Int;
--EXECERRO
ALTER TABLE POCATPDO ADD BLFITPDO Int;
--EXECERRO
ALTER TABLE POCATPDO ADD CODIPRAT Int;
--EXECERRO
ALTER TABLE POCATPDO ADD SGCHTPDO VarChar(050);
--EXECERRO
ALTER TABLE POCATPDO ADD SGBUTPDO VarChar(050);
--EXECERRO
ALTER TABLE POCATPDO ADD SGTBTPDO Int;
--EXECERRO
ALTER TABLE POCATPDO ADD SF16TPDO Int;
--EXECERRO
------------------------------------------------------
