
--  *************************************************
--  *** SAG - Tabelas ***

--> 001 Tabela: SISTCAMP
------------------------------------------------------
CREATE TABLE SISTCAMP (CODICAMP Int IDENTITY (1, 1) NOT NULL);
--EXECERRO
ALTER TABLE SISTCAMP ADD CONSTRAINT PK_SISTCAMP PRIMARY KEY (CODICAMP);
--EXECERRO
ALTER TABLE SISTCAMP ADD CODITABE Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD NOMECAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD LABECAMP VarChar(500);
--EXECERRO
ALTER TABLE SISTCAMP ADD HINTCAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD NOSQCAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD TOPOCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD MTOPCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD ESQUCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD MESQCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD TAMACAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD TIPOCAMP VarChar(040);
--EXECERRO
ALTER TABLE SISTCAMP ADD ORDECAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD OBRICAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD GUIACAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD MASCCAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD MINICAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD MAXICAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD LISTCAMP VarChar(020);
--EXECERRO
ALTER TABLE SISTCAMP ADD DECICAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD DROPCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD TABECAMP VarChar(020);
--EXECERRO
ALTER TABLE SISTCAMP ADD PESQCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD PADRCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD ALTUCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD FORMCAMP VarChar(040);
--EXECERRO
ALTER TABLE SISTCAMP ADD ESTICAMP VarChar(040);
--EXECERRO
ALTER TABLE SISTCAMP ADD DESACAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD FIXOCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD COLUCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD COESCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD LINHCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD LIESCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD LFONCAMP VarChar(020);
--EXECERRO
ALTER TABLE SISTCAMP ADD LCORCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD LESTCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD LEFECAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD CFONCAMP VarChar(020);
--EXECERRO
ALTER TABLE SISTCAMP ADD CTAMCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD CCORCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD CESTCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD CEFECAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD LTAMCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD INTECAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD EXISCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD OBS_CAMP Image;
--EXECERRO
ALTER TABLE SISTCAMP ADD TAGQCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD PEMPCAMP VarChar(3);
--EXECERRO
ALTER TABLE SISTCAMP ADD PUSUCAMP VarChar(3);
--EXECERRO
ALTER TABLE SISTCAMP ADD PSISCAMP VarChar(3);
--EXECERRO
ALTER TABLE SISTCAMP ADD PERSCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD PDATCAMP DateTime;
--EXECERRO
ALTER TABLE SISTCAMP ADD FIGUCAMP Image;
--EXECERRO
ALTER TABLE SISTCAMP ADD POCOCONS Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD NAMECAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD NOANCAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD EXPRCAMP Text;
--EXECERRO
ALTER TABLE SISTCAMP ADD SQL_CAMP Text;
--EXECERRO
ALTER TABLE SISTCAMP ADD COMPCAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD CODTTABE Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD INICCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD EPERCAMP Text;
--EXECERRO
ALTER TABLE SISTCAMP ADD VERSCAMP VarChar(040);
--EXECERRO
ALTER TABLE SISTCAMP ADD GRCOCAMP Text;
--EXECERRO
ALTER TABLE SISTCAMP ADD ID__CAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD POEMCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD SAG_CAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD LBCXCAMP Int;
--EXECERRO
ALTER TABLE SISTCAMP ADD VARECAMP Text;
--EXECERRO
ALTER TABLE SISTCAMP ADD VAGRCAMP Text;
--EXECERRO
ALTER TABLE SISTCAMP ADD CODIPRAT Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD RESPCAMP VarChar(250);
--EXECERRO
ALTER TABLE SISTCAMP ADD SGBUCAMP VarChar(050);
--EXECERRO
ALTER TABLE SISTCAMP ADD SGCHCAMP VarChar(050);
--EXECERRO
ALTER TABLE SISTCAMP ADD SGCICAMP VarChar(100);
--EXECERRO
ALTER TABLE SISTCAMP ADD SGTBCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SALTCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SCOECAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SCOLCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SESQCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SFIXCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SGUICAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SLIECAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SLINCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SMESCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SMTOCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD SORDCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD STAMCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD STOPCAMP Float;
--EXECERRO
ALTER TABLE SISTCAMP ADD EXP1CAMP Text;
--EXECERRO
ALTER TABLE SISTCAMP ADD CAPTCAMP Int;
--EXECERRO
------------------------------------------------------
